# Generated by Django 4.2.6 on 2023-10-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbooks',
            name='auther',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
