# Generated by Django 4.2.5 on 2023-10-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='auther',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book/images/'),
        ),
    ]
